language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.5 CMS_VERSION=3.0
  - DJANGO_VERSION=1.6 CMS_VERSION=3.0
  - DJANGO_VERSION=1.7 CMS_VERSION=3.0
  - DJANGO_VERSION=1.6 CMS_VERSION=3.1
  - DJANGO_VERSION=1.7 CMS_VERSION=3.1
  - DJANGO_VERSION=1.8 CMS_VERSION=3.1

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=1.5
    - python: "3.5"
      env: DJANGO_VERSION=1.6
    - python: "3.5"
      env: DJANGO_VERSION=1.7

install:
  - pip install tox>=2.0

script: tox -e py${TRAVIS_PYTHON_VERSION/./}-django${DJANGO_VERSION}-cms${CMS_VERSION},pep8
